### ISSUE TITLE
It doesn't allow multiple files uploads...

### ISSUE THREAD

**Issue by barshag** [codersteps/nextjs_file_uploader#1]

**Comment by abdessamadelhamdany** [comment]
Hey @barshag 
Have you tried increasing the `maxFiles`/`maxFileSize` on the `lib/parse-form.ts` file?

**Comment by barshag** [comment]
Yea. It seems that the client side doesn't support showing multiple files...

**Comment by barshag** [comment]
Unfortunately I didn't succeed in  making it (both in front and Backend)

**In Backend**:
I switch the frontend and didn't succeed either.
Seems like the multiple files don't enter "parseForm" in "parse-form.ts", cause I can them in "form.parse".
EVEN if i add  "  multiples: true" to  formidable object (along with increasing the #files to 30, and huge filesize....

**In frontend**:

I'm trying to add items (when capturing e.target.files add event).

Here is the Hook of File arrray:

    const [fileso, setFileso] = useState<File[] |null>(null);



Here is the event that I'm capture:

 <form  className="w-max p-3 border border-gray-500 border-dashed"
              action="" onSubmit={(e:any)=> e.preventDefault()}>




Here is the problem:

const onFileUploadChange = (e: React.ChangeEvent<HTMLInputElement>) => {

     const fileInput =  e.target;

 const files = fileInput.files;

      for (let i=0; i<files.length;i++)
      {
     
        setFileso(previous => [...previous,files[i]]); <-----problem
        setPreviewUrl(URL.createObjectURL(file));

         }
   }





:(

So, I need some help :) - seems that it doesn't that trivial, after all

**Comment by abdessamadelhamdany** [comment]
Hello @barshag 

I will add an extra section tonight to explain how to extend it to handle multiple uploads
I think it will be easy for me to help you, and maybe others in the future
So you can recheck the post tomorrow 

Thank you for sharing 🙏

**Comment by barshag** [comment]
Awesome, thanks!
Really appreciate it!

**Comment by abdessamadelhamdany** [comment]
Hello @barshag 
I have completed the multiple upload section on the related article, Please feel free to check it out, Also I want to mention that I have done some changes to the parse-form file.

You can check all the changes in this [commit](https://github.com/codersteps/nextjs_file_uploader/commit/1fd4f7d8b1a4808b74e1a17ff2d00d4966d7d15f)

I hope this can help

**Comment by barshag** [comment]
The changes in the server are working!!- tomorrow I'll check the client! :)
:)

I have to mention that your availability, desire to help and of course your
tech-knowledge are remarkable!

You made my day :)

Thanks again!

**Comment by abdessamadelhamdany** [comment]
Happy I could help 🙏

**Comment by barshag** [comment]
Hi!
Update:

Basically it works and perform a shortcut on the part that I most  struggle with...  :)

**Making  validFiles working as REACT-HOOK**.

I need it because, that's allow the same mechanism as uploading only one file ( via a "Upload button").
Do you have any suggestion how to refactor  "validFiles" into an Hook.

(I struggle with the syntax of updating values of ARRAY of files....)


Thanks again!

**Comment by abdessamadelhamdany** [comment]
Hello,
 
Do you mean, a hook that takes the `target.files` array and return valid files?
The only update to the validFiles array, is the `.push` which add a file when its valid

if you mean this one:
```ts
validFiles.forEach((file) => formData.append("media", file));
```
it just loop through the validFiles and append them to the formData

I'm not sure I understand the issue you're facing, and what the hook should take as arguments, and what should it return

Let me know!

**Comment by barshag** [comment]
Yes I'm talking about a hook that takes the target.files, and then makes it
possible to remove files, and show them... (with other events -
OnCancel/OnUpload, etc..)
The issue is that  Hook forced me to use  a function to update the value ->
and I got lost with the syntax and the loop of how to handle "setting"
values to an **array**.
Especially with Typescript.

I hope I have made myself clearer - tell me if still not :)

**Comment by abdessamadelhamdany** [comment]
Could you send me an email, lets continue the discussion there!

**Comment by barshag** [comment]
Sure!

This is your ***@***.*** ?

**Comment by abdessamadelhamdany** [comment]
Yes the one on my profile
