### ISSUE TITLE
Build Error  in parse-form

### ISSUE THREAD

**Issue by barshag** [codersteps/nextjs_file_uploader#2]
In:
/src/libs/parse-form.ts
  11:15  error    Promise executor functions should not be async  no-async-promise-executor

In this decleration:

```JS
export const parseForm = async (
  req: NextApiRequest
): Promise<{ fields: formidable.Fields; files: formidable.Files }> => {
  return await new Promise(async (resolve, reject) => {
    const uploadDir = join(
      process.env.ROOT_DIR || process.cwd(),
      `/uploads/${dateFn.format(Date.now(), "dd-MM-Y")}`
    );

```

**Comment by abdessamadelhamdany** [comment]
Hey @barshag 

Thank you for your feedback, maybe it's caused by a newer `next js` version than the one being used in the tutorial, I'm planning on updating all articles to use `next js 13`.

In the meanwhile please share you're `package.json` file, I will try to check it out, and see if I can help.

**Comment by barshag** [comment]
Yea! I really liked your tutorial (follow it, till the end)!
Next 13-  is an interesting point.

Here is the package.json:


{
"name": "startd-theme",
"description": "Landing page!",
"version": "1.0.0",
"private": true,
"author": ",
"license": "MIT",
"keywords": [
"nextjs",
"starter",
"typescript",
"tailwind",
"theme"
],
"scripts": {
"dev": "next",
"build": "next build",
"start": "next start",
"type-check": "tsc",
"lint": "eslint --ignore-path .gitignore \"src/**/*.+(ts|js|tsx)\"",
"format": "prettier --ignore-path .gitignore \"src/**/*.+(ts|js|tsx)\"
--write",
"postinstall": "husky install"
},
"lint-staged": {
"./src/**/*.{ts,js,jsx,tsx}": [
"yarn lint --fix",
"yarn format"
]
},
"dependencies": {
***@***.***/inter": "4.2.1",
***@***.***/webpack": "5.5.0",
***@***.***/form-data": "2.5.0",
***@***.***/formidable": "2.0.5",
***@***.***/mime": "3.0.1",
***@***.***/multer": "1.4.7",
"date-fns": "2.29.3",
"form-data": "4.0.0",
"mailgun.js": "8.0.6",
"mime": "3.0.0",
"next": "10.0.7",
"next-seo": "4.20.0",
"react": "17.0.1",
"react-dom": "17.0.1",
"react-particles-js": "3.4.1",
"twind": "0.15.4"
},
"devDependencies": {
***@***.***/cli": "11.0.0",
***@***.***/config-conventional": "11.0.0",
***@***.***/node": "14.14.28",
***@***.***/react": "17.0.2",
***@***.***/react-dom": "17.0.1",
***@***.***/eslint-plugin": "4.15.1",
***@***.***/parser": "4.15.1",
"commitizen": "4.2.3",
"cz-conventional-changelog": "3.3.0",
"eslint": "7.20.0",
"eslint-config-airbnb": "18.2.1",
"eslint-config-prettier": "7.2.0",
"eslint-import-resolver-typescript": "2.4.0",
"eslint-plugin-import": "2.22.1",
"eslint-plugin-jsx-a11y": "6.4.1",
"eslint-plugin-prettier": "3.3.1",
"eslint-plugin-react": "7.22.0",
"eslint-plugin-react-hooks": "4.2.0",
"formidable": "2.0.1",
"husky": "5.0.9",
"lint-staged": "10.5.4",
"prettier": "2.2.1",
"typescript": "4.1.5"
},
"config": {
"commitizen": {
"path": "cz-conventional-changelog"
}
}
}

**Comment by abdessamadelhamdany** [comment]
Hey again
I'm not able to get it to work with the provided `package.json`, it looks like a custom setup so I'm not sure I can help in this case.

But as I mentioned before, Could you please remove the `await` keyword, so it becomes:
```typescript
    return new Promise(async (resolve, reject) => {
```

As mentioned in this StackOverflow: https://stackoverflow.com/questions/43083696/cant-throw-error-from-within-an-async-promise-executor-function

I'm glad you liked the article 🙏

Good luck 😊
